# Generated by Django 3.2.3 on 2024-03-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
