# Generated by Django 3.2.3 on 2024-04-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20240413_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['-created'], name='store_comme_created_022095_idx'),
        ),
    ]
