# Generated by Django 3.2.3 on 2024-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Confirmed Oreder', 'Confirmed Oreder'), ('Processing', 'Processing'), ('Shipping', 'Shipping')], default=('Processing', 'Processing'), max_length=50),
        ),
    ]
