# Generated by Django 3.2.3 on 2024-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Rejection', 'Rejection'), ('Processing', 'Processing'), ('Shipping', 'Shipping')], max_length=50),
        ),
    ]
