# Generated by Django 3.2.3 on 2024-03-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='seller',
        ),
    ]
