# Generated by Django 3.2.3 on 2024-04-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20240414_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='seller',
        ),
    ]
